# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindowftcontroller.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        screen = QtWidgets.QApplication.desktop()
        screenGeometry = screen.screenGeometry()
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(907, 655)
        MainWindow.setGeometry(50, 50, screenGeometry.width() - 100, screenGeometry.height() - 100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_2.addWidget(self.addBtn)
        self.removeBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.removeBtn.setObjectName("removeBtn")
        self.verticalLayout_2.addWidget(self.removeBtn)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.scanArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scanArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scanArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scanArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scanArea.setWidgetResizable(True)
        self.scanArea.setObjectName("scanArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 247, 557))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scanArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scanArea)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.splitter.setSizes([1, 0])
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.downloadBtn = QtWidgets.QPushButton(self.widget)
        self.downloadBtn.setObjectName("downloadBtn")
        self.gridLayout.addWidget(self.downloadBtn, 0, 0, 1, 1)
        self.uploadBtn = QtWidgets.QPushButton(self.widget)
        self.uploadBtn.setObjectName("uploadBtn")
        self.gridLayout.addWidget(self.uploadBtn, 1, 0, 1, 1)
        self.runBtn = QtWidgets.QPushButton(self.widget)
        self.runBtn.setObjectName("runBtn")
        self.gridLayout.addWidget(self.runBtn, 0, 1, 1, 1)
        self.stopBtn = QtWidgets.QPushButton(self.widget)
        self.stopBtn.setObjectName("stopBtn")
        self.gridLayout.addWidget(self.stopBtn, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.announcer = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.announcer.sizePolicy().hasHeightForWidth())
        self.announcer.setSizePolicy(sizePolicy)
        self.announcer.setReadOnly(True)
        self.announcer.setObjectName("announcer")
        self.verticalLayout.addWidget(self.announcer)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Scan = QtWidgets.QAction(MainWindow)
        self.actionNew_Scan.setObjectName("actionNew_Scan")
        self.actionLoad_Scan = QtWidgets.QAction(MainWindow)
        self.actionLoad_Scan.setObjectName("actionLoad_Scan")
        self.actionSave_Scan = QtWidgets.QAction(MainWindow)
        self.actionSave_Scan.setObjectName("actionSave_Scan")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbort = QtWidgets.QAction(MainWindow)
        self.actionAbort.setObjectName("actionAbort")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_Scan)
        self.menuFile.addAction(self.actionLoad_Scan)
        self.menuFile.addAction(self.actionSave_Scan)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbort)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.removeBtn.setText(_translate("MainWindow", "Remove"))
        self.downloadBtn.setText(_translate("MainWindow", "Download"))
        self.uploadBtn.setText(_translate("MainWindow", "Upload"))
        self.runBtn.setText(_translate("MainWindow", "Run"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Scan.setText(_translate("MainWindow", "New Scan"))
        self.actionLoad_Scan.setText(_translate("MainWindow", "Load Scan"))
        self.actionSave_Scan.setText(_translate("MainWindow", "Save Scan"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbort.setText(_translate("MainWindow", "Abort"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

